name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm" # <-- This depends on having package-lock.json

      - name: Install dependencies
        run: npm ci # or npm install if ci fails

      - name: Run lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present
