name: Deploy Docs to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
